### ISSUE TITLE
Compiling error when getting struct-array as return.

### ISSUE THREAD

**Issue by marius1909** [internet-sicherheit/proof-of-visit-dapp#19] opened 2020-05-14 09:01 UTC
**TokenManager.sol**
` Location[] public locations;
`
```
function getLocations() public view returns (Location[] memory)
   
   {
   	return locations;
   }
```

**TestTokenManager.sol**
//Compiling this below gives an error:
TestTokenManager.sol:58:1: TypeError: Type struct TokenManager.Location memory[] memory is not implicitly convertible to expected type struct TestTokenManager.Location memory[] memory.
Location[] memory locations = povtoken.getLocations();

```
function testCreateLocation() public
{

povtoken.createLocation(_tokenname, _tokensymbol, _locationname, _locationWalletAddress);

Location[] memory locations = povtoken.getLocations();
}
```

**both contracts define this struct:**
`struct Location{
        
        string tokenname;
        string tokensymbol;
        string locationname;
        address locationaddress;
        uint256 locationID;
        
    }
`

**Comment by kiview** [comment] 2020-05-14 09:59
So the problem is the following:
Both contracts to define a struct that has potentially the same memory layout, yes. But they still have a different type and we, therefore, we a type error by the compiler.

`TokenManager.Location != TestTokenManager.Location`

This is not fundamentally different from what you observe in the Java type system. I am not an expert on the Solidity type system here, but it tells us, Solidity does not use duck typing or implicit traits/interfaces, based on shape of structures (as Go might do).

**Comment by marius1909** [comment] 2020-05-14 10:42
So i can get the struct from the function "getLocations" from Tokenmanager into my testclass but then can not work with it? I want to access the data of the struct inside my testclass. I tried to find a solution online but had no success.

**Comment by kiview** [comment] 2020-05-14 10:43
So, I fixed the type error in:
https://github.com/internet-sicherheit/proof-of-visit-dapp/commit/1789e245d8abe26ed6ccf3bbf8926cc9baac295f#diff-9a0576804c5f64a0152cf17e0835df64R48

We now get the compile error:
```
UnimplementedFeatureError: Nested arrays not yet implemented.
```
Since I am not that deep in your code yet, I am not sure if this is expected to happen or not and if this is a separate issue. If yes, we can close this issue here. 

I also reformatted all Solidity files, so I could read them without getting eye cancer :vomiting_face:  :stuck_out_tongue_winking_eye:

**Comment by marius1909** [comment] 2020-05-14 10:48
So yeah it looks like this is just not possible the way i want to do it. Need to find another way to test this function.

**Closed as completed** 2020-05-14 13:14 UTC
Labels: SmartContract
